Assignment 2/book/urls.py
from django.shortcuts import render
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from .views import *
from .views_api import *

app_name = 'books'

# Create your views here.

urlpatterns = [
	path('', homepage, name="homepage"),
	path('report/', view_report, name="view-report"),
	path('report/items/<str:code>/list/', view_item_list, name='view-item-list'),
	path('report/items/<str:code>/', view_stock_detail, name='view-stock-detail'),
	path('report/items/<str:code>/details/', view_stock_detail, name='view-stock-detail'),
	path('report/items/<str:code>/<str:start_date>/<str:end_date>/', view_report_range, name='view-report-range'),

	path('api/purchase/<str:code>/details/', PurchaseDetailViewSet.as_view({'get': 'list', 'get': 'retrieve'}), name='purchase-detail'),
	path('api/sell/<str:code>/details/', SellDetailViewSet.as_view({'get': 'list', 'get': 'retrieve'}), name='sell-detail'),
	path('api/report/<str:code>/', ReportDetailViewSet.as_view({'get': 'list', 'get': 'retrieve'}), name='report-detail'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Assignment 2/takekima/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls
from rest_framework import routers
from rest_framework.routers import DefaultRouter
from rest_framework import permissions

from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_nested import routers

from book.views import *
from book.views_api import *

router = routers.DefaultRouter()
router.register(r'items', ItemViewSet, basename='item')
router.register(r'purchase', PurchaseViewSet, basename='purchase')
router.register(r'sell', SellViewSet, basename='sell')
router.register(r'report', ReportViewSet, basename='report')

schema_view = get_schema_view(
   openapi.Info(
      title="Takekima API",
      default_version='v1',
      description="API documentation for Takekima app",
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
    path('api/', include(router.urls)),
    path('api/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Assignment 2/templates/footers.html
{% load static %}

{% block footers %}
		<!-- footer @s -->
			<div class="nk-footer">
				<div class="container-fluid">
					<div class="nk-footer-wrap">
						<div class="nk-footer-copyright"> &copy; 2025 Stock Inventory by <a href="javascript:void" >Takekima</a>
						</div>
						<div class="nk-footer-links">
							<ul class="nav nav-sm">
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!-- footer @e -->
		</div>
	</div>
<!-- main @e -->
</div>
{% endblock footers %}

Assignment 2/templates/headers.html
{% load static %}

{% block headers %}

 <div class="nk-app-root">
        <!-- main @s -->
        <div class="nk-main ">
             <!-- sidebar @s -->
            <div class="nk-sidebar nk-sidebar-fixed is-light " data-content="sidebarMenu">
                <div class="nk-sidebar-element nk-sidebar-head">
                    <div class="nk-sidebar-brand">
                        <a href="/" class="logo-link nk-sidebar-logo">
                            <img class="logo-light logo-img" src="{% static 'images/logo.png' %}" srcset="./images/logo2x.png 2x" alt="logo">
                            <img class="logo-dark logo-img" src="{% static 'images/logo-dark.png' %}" srcset="./images/logo-dark2x.png 2x" alt="logo-dark">
                            <img class="logo-small logo-img logo-img-small" src="{% static 'images/logo-small.png' %}" srcset="./images/logo-small2x.png 2x" alt="logo-small">
                        </a>
                    </div>
                    <div class="nk-menu-trigger mr-n2">
                        <a href="#" class="nk-nav-toggle nk-quick-nav-icon d-xl-none" data-target="sidebarMenu"><em class="icon ni ni-arrow-left"></em></a>
                        <a href="#" class="nk-nav-compact nk-quick-nav-icon d-none d-xl-inline-flex" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
                    </div>
                </div><!-- .nk-sidebar-element -->
                <div class="nk-sidebar-element">
                    <div class="nk-sidebar-content">
                        <div class="nk-sidebar-menu" data-simplebar>
                            <ul class="nk-menu">
                                 {% if request.user.is_authenticated %}
                                <li class="nk-menu-heading">
                                    <h6 class="overline-title text-primary-alt">Navigation</h6>
                                </li><!-- .nk-menu-item -->
                                  <li class="nk-menu-item">
                                    <a href="/" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-home-fill"></em></span>
                                        <span class="nk-menu-text">Home</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                <li class="nk-menu-item">
                                    <a href="/api" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-list-index-fill"></em></span>
                                        <span class="nk-menu-text">API</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                <li class="nk-menu-item">
                                    <a href="/api/docs" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-list-index"></em></span>
                                        <span class="nk-menu-text">API Docs</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                <li class="nk-menu-item">
                                    <a href="{% url 'books:view-report' %}" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-reports"></em></span>
                                        <span class="nk-menu-text">Report</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                <li style="display:none" class="nk-menu-item">
                                    <a href="/scrumboard" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-note-add"></em></span>
                                        <span class="nk-menu-text">Scrumboard</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                 <li class="nk-menu-item">
                                    <a href="/contacts" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="icon ni ni-note-add"></em></span>
                                        <span class="nk-menu-text">Contacts</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                  {% endif %}
                                {% if request.user.is_authenticated %}
                                <li style="display:none" class="nk-menu-item">
                                    <a href="{% url 'logout' %}" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="ni ni-signout"></em></span>
                                        <span class="nk-menu-text">Log Out</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                 {% else %}
                                <li class="nk-menu-item">
                                    <a href="{% url 'login' %}" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="ni ni-signin"></em></span>
                                        <span class="nk-menu-text">Log In</span>
                                    </a>
                                </li>
                                <li class="nk-menu-item">
                                    <a href="{% url 'register' %}" class="nk-menu-link">
                                        <span class="nk-menu-icon"><em class="ni ni-user-add"></em></span>
                                        <span class="nk-menu-text">Register</span>
                                    </a>
                                </li><!-- .nk-menu-item -->
                                {% endif %}
                            </ul><!-- .nk-menu -->
                        </div><!-- .nk-sidebar-menu -->
                    </div><!-- .nk-sidebar-content -->
                </div><!-- .nk-sidebar-element -->
            </div>
            <!-- sidebar @e -->
            <!-- wrap @s -->
            <div class="nk-wrap ">
                <!-- main header @s -->
                <div class="nk-header nk-header-fixed is-light">
                    <div class="container-fluid">
                        <div class="nk-header-wrap">
                            <div class="nk-menu-trigger d-xl-none ml-n1">
                                <a href="#" class="nk-nav-toggle nk-quick-nav-icon" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
                            </div>
                            <div class="nk-header-brand d-xl-none">
                                <a href="/" class="logo-link">
                                    <img class="logo-light logo-img" src="{% static 'images/logo.png' %}" srcset="./images/logo2x.png 2x" alt="logo">
                                    <img class="logo-dark logo-img" src="{% static 'images/logo-dark.png' %}" srcset="./images/logo-dark2x.png 2x" alt="logo-dark">
                                </a>
                            </div><!-- .nk-header-brand -->
                            <div class="nk-header-search ml-3 ml-xl-0">
                                <em class="icon ni ni-search"></em>
                                <input type="text" class="form-control border-transparent form-focus-none" placeholder="Search anything">
                            </div><!-- .nk-header-news -->
                            <div class="nk-header-tools">
                                <ul class="nk-quick-nav">
                                    <li class="dropdown user-dropdown">
                                        <a href="#" class="dropdown-toggle mr-n1" data-toggle="dropdown">
                                            <div class="user-toggle">
                                                <div class="user-avatar sm">
                                                    <em class="icon ni ni-user-alt"></em>
                                                </div>
                                                <div class="user-info d-none d-xl-block">
                                                    <div class="user-name dropdown-indicator">{{ user }}</div>
                                                </div>
                                            </div>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-md dropdown-menu-right">
                                            <div class="dropdown-inner user-card-wrap bg-lighter d-none d-md-block">
                                                <div class="user-card">
                                                    <div class="user-avatar">
                                                        <span>AB</span>
                                                    </div>
                                                    <div class="user-info">
                                                        <span class="lead-text">{{ user }}</span>
                                                        {% if request.user.is_authenticated %}
                                                        <span class="sub-text">{{ user.email }}</span>
                                                        {% else %}
                                                        <span class="sub-text"></span>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="dropdown-inner">
                                                <ul class="link-list">
                                                    <li><a class="dark-switch" href="#"><em class="icon ni ni-moon"></em><span>Dark Mode</span></a></li>
                                                </ul>
                                            </div>
                                            <div class="dropdown-inner">
                                                <ul class="link-list">
                                                      {% if request.user.is_authenticated %}
                                                    <li>
                                                        <form action="{% url 'logout' %}" method="post">
                                                        {% csrf_token %}
                                                            <a type="submit" style="cursor: pointer;" onclick="this.closest('form').submit();return false;"><em class="icon ni ni-signout"></em><span>Log out</span></a>
                                                        </form>
                                                    </li>
                                                    {% else %}
                                                    <li><a href="{% url 'login' %}"><em class="icon ni ni-signin"></em><span>Log In</span></a></li>
                                                     {% endif %}
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div><!-- .nk-header-wrap -->
                    </div><!-- .container-fliud -->
                </div>
                <!-- main header @e -->
                <!-- content @s -->

                <!-- content @e -->


            <!-- wrap @e -->
{% endblock headers %}

Assignment 2/templates/homepage.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Homepage
{% endblock title %}

{% block content %}

<div class="nk-content ">
    <div class="container-fluid">
        <div class="nk-content-inner">
            <div class="nk-content-body">
               <div class="nk-block-head nk-block-head-sm">
                    <div class="nk-block-between">
                        <div class="nk-block-head-content">
                            <h3 class="nk-block-title page-title">Homepage</h3>
                        </div><!-- .nk-block-head-content -->
                        <div class="nk-block-head-content">
                            <div class="toggle-wrap nk-block-tools-toggle">
                                <a href="#" class="btn btn-icon btn-trigger toggle-expand mr-n1" data-target="pageMenu"><em class="icon ni ni-more-v"></em></a>
                                <div class="toggle-expand-content" data-content="pageMenu">
                                    <ul class="nk-block-tools g-3">
                                        <li class="nk-block-tools-opt"><a href="{% url 'books:view-report' %}" class="btn btn-primary"><em class="icon ni ni-reports"></em><span>Reports</span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div><!-- .nk-block-head-content -->
                    </div><!-- .nk-block-between -->
                </div><!-- .nk-block-head -->

                <div class="nk-block">
                    <div class="row g-gs">

                         <div class="col-xxl-6">
                            <div class="card card-full">
                                <div class="nk-ecwg nk-ecwg8 h-100">
                                    <div class="card-inner">
                                        <div class="card-title-group mb-3">
                                            <div class="card-title">
                                                <h6 class="title">Takekima Test</h6>
                                            </div>
                                        </div>
                                        <div class="nk-ecwg8-ck">
                                          <canvas class="line-chart chartjs-render-monitor" id="solidLineChart" width="327" height="225" style="display: block; height: 180px; width: 262px;"></canvas>
                                        </div>
                                        <div class="chart-label-group pl-5">
                                            <div class="chart-label"></div>
                                            <div class="chart-label">{% now "jS-F-Y: H:i" %}</div>
                                        </div>
                                    </div><!-- .card-inner -->
                                </div>
                            </div><!-- .card -->
                        </div><!-- .col -->
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

{% endblock content %}

Assignment 2/templates/view_item_list.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Stock Report
{% endblock title %}

{% block content %}
<div class="nk-content ">
	<div class="container-fluid">
		<div class="nk-content-inner">
			<div class="nk-content-body">
				<div class="components-preview wide-md mx-auto">
					 <div class="nk-block nk-block-lg">
						<div class="nk-block-head">
							<div class="nk-block-head-content">
								<h4 class="nk-block-title">{{ title }}</h4>
							</div>
							<br />
							<div class="nk-block-content">
								<h6 class="nk-block-title fw-normal">Code: {{ datas.code }}</h6>
								<h6 class="nk-block-title fw-normal">Name: {{ datas.name }}</h6>
							</div>
						</div>

						<table class="nowrap nk-tb-list is-separate" data-auto-responsive="false">
							<thead>
								<tr class="nk-tb-item nk-tb-head">
									<th class="nk-tb-col tb-col-sm"><span>ID</span></th>
									<th class="nk-tb-col"><span>CODE</span></th>
									<th class="nk-tb-col"><span>DATE</span></th>
									<th class="nk-tb-col tb-col-md"><span>DESCRIPTION</span></th>
									<th class="nk-tb-col nk-tb-col-tools">
										<ul class="nk-tb-actions gx-1 my-n1">
											<li class="mr-n1">
												<div class="dropdown">
													<a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown">ACTION</a>
												</div>
											</li>
										</ul>
									</th>
								</tr><!-- .nk-tb-item -->
							</thead>
							<tbody>

							   {% for every in item_data %}
								<tr class="nk-tb-item">
									<td class="nk-tb-col tb-col-sm">
										<span class="tb-sub">
											<span class="title">{{ forloop.counter }}</span>
										</span>
									</td>

									<td class="nk-tb-col">
										<span class="tb-lead"><a href="{% url 'books:view-stock-detail' every.code %}">{{ every.code }}</a></span>
									</td>
									<td class="nk-tb-col">
										<span class="tb-sub">{{ every.date }}</span>
									</td>
									<td class="nk-tb-col tb-col-md">
										<span class="tb-sub">{{ every.description }}</span>
									</td>
									<td class="nk-tb-col nk-tb-col-tools">
										<ul class="nk-tb-actions gx-1 my-n1">
											<li class="mr-n1">
												<div class="dropdown">
													<a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
													<div class="dropdown-menu dropdown-menu-right">
														<ul class="link-list-opt no-bdr">
															<li><a href="{% url 'books:view-stock-detail' every.code %}"><em class="icon ni ni-edit"></em><span>Edit Book</span></a></li>
															<li><a href="{% url 'books:view-stock-detail' every.code %}"><em class="icon ni ni-eye"></em><span>View Book</span></a></li>
															<li><a id="{{ forloop.counter }}"  href="javascript:void(0)"><em class="icon ni ni-trash"></em><span>Remove Book</span></a></li>
														</ul>
													</div>
												</div>
											</li>
										</ul>
									</td>
								</tr><!-- .nk-tb-item -->
							 {% endfor %}
							</tbody>
						</table><!-- .nk-tb-list -->
					</div> <!-- nk-block -->

				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block footers %}
{{ block.super }}
{% endblock %}

{% block scripts %}
{{ block.super }}
<script src="{% static 'js/report.js' %}" type="text/javascript"></script>
{% endblock scripts %}

Assignment 2/templates/view_report.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Stock Report
{% endblock title %}

{% block content %}
<div class="nk-content ">
	<div class="container-fluid">
		<div class="nk-content-inner">
			<div class="nk-content-body">
				<div class="components-preview wide-md mx-auto">
					 <div class="nk-block nk-block-lg">
						<div class="nk-block-head">
							<div class="nk-block-head-content">
								<h4 class="nk-block-title">{{ title }}</h4>
							</div>
						</div>


						<form method="POST" action="" name="itemForm" class="row row-cols-lg-auto align-items-center" style="display:ruby-text">
						{% csrf_token %}

							<div class="col-3">
								<label class="visually">Item</label>
								<div class="input-group">
									<select class="form-select" id="selectItem">
										<option selected>Choose...</option>
										{% for item in item_data %}
										<option value="{{ item.code }}">{{ item.code }}</option>
										{% endfor %}
									</select>
								</div>
							</div>

							<div class="col-3">
								<label class="visually">From Date</label>
								<div class="input-group">
									<input type="text" id="start_date" class="form-control date-picker" data-date-format="yyyy-mm-dd">
									<div class="form-icon form-icon-right"><em class="icon ni ni-calendar"></em></div>
								</div>
							</div>

							<div class="col-3">
								<label class="visually">To Date</label>
								<div class="input-group">
									<input type="text" id="end_date" class="form-control date-picker" data-date-format="yyyy-mm-dd">
									<div class="form-icon form-icon-right"><em class="icon ni ni-calendar"></em></div>
								</div>
							</div>

							<div class="col-3">
								<button id="btnSubmit" type="submit" class="btn btn-primary">Submit</button>
							</div>
						</form>

						<table class="nowrap nk-tb-list is-separate" data-auto-responsive="false">
							<thead>
								<tr class="nk-tb-item nk-tb-head">
									<th class="nk-tb-col tb-col-sm"><span>ID</span></th>
									<th class="nk-tb-col"><span>CODE</span></th>
									<th class="nk-tb-col"><span>NAME</span></th>
									<th class="nk-tb-col tb-col-md"><span>DESCRIPTION</span></th>
									<th class="nk-tb-col tb-col-md"><span>STOCK</span></th>
									<th class="nk-tb-col tb-col-md"><span>UNIT</span></th>
									<th class="nk-tb-col tb-col-md"><span>BALANCE</span></th>
									<th class="nk-tb-col nk-tb-col-tools">
										<ul class="nk-tb-actions gx-1 my-n1">
											<li class="mr-n1">
												<div class="dropdown">
													<a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown">ACTION</a>
												</div>
											</li>
										</ul>
									</th>
								</tr><!-- .nk-tb-item -->
							</thead>
							<tbody>

							   {% for every in item_data %}
								<tr class="nk-tb-item">
									<td class="nk-tb-col tb-col-sm">
										<span class="tb-sub">
											<span class="title">{{ forloop.counter }}</span>
										</span>
									</td>

									<td class="nk-tb-col">
										<span class="tb-lead"><a href="{% url 'books:view-item-list' every.code %}">{{ every.code }}</a></span>
									</td>
									<td class="nk-tb-col">
										<span class="tb-sub">{{ every.name }}</span>
									</td>
									<td class="nk-tb-col tb-col-md">
										<span class="tb-sub">{{ every.description }}</span>
									</td>
									<td class="nk-tb-col tb-col-md">
										<span class="tb-sub">{{ every.stock }}</span>
									</td>
									<td class="nk-tb-col tb-col-md">
										<span class="tb-sub">{{ every.unit }}</span>
									</td>
									<td class="nk-tb-col tb-col-md">
										<span class="tb-sub">{{ every.balance }}</span>
									</td>
									<td class="nk-tb-col nk-tb-col-tools">
										<ul class="nk-tb-actions gx-1 my-n1">
											<li class="mr-n1">
												<div class="dropdown">
													<a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
													<div class="dropdown-menu dropdown-menu-right">
														<ul class="link-list-opt no-bdr">
															<li><a href="{% url 'books:view-item-list' every.code %}"><em class="icon ni ni-edit"></em><span>Edit Book</span></a></li>
															<li><a href="{% url 'books:view-item-list' every.code %}"><em class="icon ni ni-eye"></em><span>View Book</span></a></li>
															<li><a id="{{ forloop.counter }}"  href="javascript:void(0)"><em class="icon ni ni-trash"></em><span>Remove Book</span></a></li>
														</ul>
													</div>
												</div>
											</li>
										</ul>
									</td>
								</tr><!-- .nk-tb-item -->
							 {% endfor %}
							</tbody>
						</table><!-- .nk-tb-list -->
					</div> <!-- nk-block -->

				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block footers %}
{{ block.super }}
{% endblock %}

{% block scripts %}
{{ block.super }}
<script src="{% static 'js/report.js' %}" type="text/javascript"></script>
{% endblock scripts %}

Assignment 2/templates/view_stock_detail.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Stock Report
{% endblock title %}

{% block content %}
<div class="nk-content ">
	<div class="container-fluid">
		<div class="nk-content-inner">
			<div class="nk-content-body">
				<div class="components-preview wide-md mx-auto">
					<div class="nk-block nk-block-lg">
						<div class="nk-block-head">
							<div class="nk-block-head-content">
								<h4 class="nk-block-title">{{ title }}</h4>
							</div>
							<br />
							<div class="nk-block-content">
								<div class="card h-100">
									<div class="card-inner">
										<h6 class="nk-block-title fw-normal">Code: {{ item_data.code }}</h6>
										<h6 class="nk-block-title fw-normal">Description: {{ item_data.description }}</h6>
									</div>
								</div>
							</div>
						</div>

					</div> <!-- nk-block -->

				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block footers %}
{{ block.super }}
{% endblock %}